version: "3.8"

services:
  martin:
    image: maplibre/martin:latest
    ports:
      - "3333:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/jasindogis
    networks:
      - gisnet

networks:
  gisnet:
    external: true
