version: '3.8'

services:
  gis-siap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gis_siap_frontend
    ports:
      - "80:80"
    networks:
      gisnet:
        aliases:
          - frontend.docker
    restart: unless-stopped


networks:
  gisnet:
    external: true
